//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> TurnID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string Value { get; set; }
        public long UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
