//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInviteToken
    {
        public int GameID { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
