//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayer
    {
        public GamePlayer()
        {
            this.Turns = new HashSet<Turn>();
        }
    
        public int GamePlayerID { get; set; }
        public long UserID { get; set; }
        public int GameID { get; set; }
        public int TurnOrder { get; set; }
        public Nullable<int> CivID { get; set; }
        public int TimesSkipped { get; set; }
        public Nullable<int> AverageTurnTime { get; set; }
        public bool DisablePasswordEncrypt { get; set; }
        public bool AllowVacation { get; set; }
    
        public virtual Civilization Civilization { get; set; }
        public virtual ICollection<Turn> Turns { get; set; }
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
