//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Comments = new HashSet<Comment>();
            this.InviteTokens = new HashSet<GameInviteToken>();
            this.Players = new HashSet<GamePlayer>();
            this.Notifications = new HashSet<Notification>();
            this.Turns = new HashSet<Turn>();
            this.Civilizations = new HashSet<Civilization>();
        }
    
        public int GameID { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<long> WinnerUserId { get; set; }
        public long HostUserId { get; set; }
        public bool Private { get; set; }
        public int MaxPlayers { get; set; }
        public Nullable<int> TurnTimeLimit { get; set; }
        public Nullable<int> SkipLimit { get; set; }
        public string TurnTimerDays { get; set; }
        public int TimeZone { get; set; }
        public Nullable<System.TimeSpan> TurnTimerStart { get; set; }
        public Nullable<System.TimeSpan> TurnTimerStop { get; set; }
        public int SteamGameID { get; set; }
        public bool AllowDLC { get; set; }
        public int Type { get; set; }
        public bool Scenario { get; set; }
        public bool AllowPublicJoin { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<GameInviteToken> InviteTokens { get; set; }
        public virtual ICollection<GamePlayer> Players { get; set; }
        public virtual SteamGame SteamGame { get; set; }
        public virtual User Host { get; set; }
        public virtual User Winner { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Turn> Turns { get; set; }
        public virtual ICollection<Civilization> Civilizations { get; set; }
    }
}
