//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRecipient
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public long RecipientUserId { get; set; }
        public bool HasNew { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User Recipient { get; set; }
    }
}
