//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int NotificationType { get; set; }
        public Nullable<long> SendingUserID { get; set; }
        public long ReceivingUserID { get; set; }
        public Nullable<int> TurnID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string CustomMessage { get; set; }
        public Nullable<System.DateTime> Checked { get; set; }
        public System.DateTime Sent { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Message Message { get; set; }
        public virtual User ReceivingUser { get; set; }
        public virtual User SendingUser { get; set; }
        public virtual Turn Turn { get; set; }
    }
}
