//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteamGame
    {
        public SteamGame()
        {
            this.Games = new HashSet<Game>();
            this.SteamGameCivilizations = new HashSet<SteamGameCivilization>();
        }
    
        public int SteamGameID { get; set; }
        public string Name { get; set; }
        public long SteamID { get; set; }
        public string ImageUrl { get; set; }
        public string SmallImageUrl { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<SteamGameCivilization> SteamGameCivilizations { get; set; }
    }
}
