//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteamGameCivilization
    {
        public int SteamGameID { get; set; }
        public int CivID { get; set; }
        public bool IsDLC { get; set; }
    
        public virtual Civilization Civilization { get; set; }
        public virtual SteamGame SteamGame { get; set; }
    }
}
