//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turn
    {
        public Turn()
        {
            this.Notifications = new HashSet<Notification>();
            this.ExpiresOn = MaxSqlDateTime;
        }
    
        public int TurnID { get; set; }
        public int GameID { get; set; }
        public long UserID { get; set; }
        public int Number { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public Nullable<int> SaveID { get; set; }
        public int Skipped { get; set; }
        public Nullable<int> GamePlayerID { get; set; }
        public int Points { get; set; }
        public Nullable<int> FileSizeInBytes { get; set; }
        public System.DateTime ExpiresOn { get; set; }
    
        public virtual GamePlayer GamePlayer { get; set; }
        public virtual Game Game { get; set; }
        public virtual Save Save { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
