//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.GamePlayers = new HashSet<GamePlayer>();
            this.GamesHosted = new HashSet<Game>();
            this.MessageRecipients = new HashSet<MessageRecipient>();
            this.Messages = new HashSet<Message>();
            this.ReceivedNotifications = new HashSet<Notification>();
            this.SentNotifications = new HashSet<Notification>();
            this.Payments = new HashSet<Payment>();
            this.Preferences = new HashSet<Preference>();
            this.Turns = new HashSet<Turn>();
        }
    
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string ProfileUrl { get; set; }
        public string AvatarUrl { get; set; }
        public string MediumAvatarUrl { get; set; }
        public string FullAvatarUrl { get; set; }
        public string Email { get; set; }
        public string AuthKey { get; set; }
        public System.DateTime LastLoggedIn { get; set; }
        public bool Premium { get; set; }
        public System.DateTime FirstLogin { get; set; }
        public int AccountTypeInt { get; set; }
        public int TotalPoints { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<GamePlayer> GamePlayers { get; set; }
        public virtual ICollection<Game> GamesHosted { get; set; }
        public virtual ICollection<MessageRecipient> MessageRecipients { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Notification> ReceivedNotifications { get; set; }
        public virtual ICollection<Notification> SentNotifications { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual ICollection<Turn> Turns { get; set; }
    }
}
