//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmrLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStat
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string AvatarUrl { get; set; }
        public int TotalPoints { get; set; }
        public int GameCount { get; set; }
        public int TurnCount { get; set; }
        public int SkipCount { get; set; }
        public int VacationCount { get; set; }
        public int AverageTurnTime { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
